import { useState } from 'react';
import { Plus, Cpu, BrainCircuit, Server, Cable, Check, Trash2, ChevronRight, X, Save, FileJson } from 'lucide-react';
import { api } from './api';
import { Modal } from './Modal';

const base = { name: '', kind: 'video', protocol: 'h3', baseUrl: 'http://127.0.0.1:30010/v1', model: '', capabilities: ['FL2VA'], apiKey: '', headers: {}, bodyTemplate: {}, extraBody: {}, responseMap: { jobId: 'id', status: 'status', videoUrl: 'video_url', audioUrl: '', successValues: ['completed', 'succeeded', 'success'], failureValues: ['failed', 'error', 'cancelled'] }, submitPath: '', pollPath: '', resultPath: '', assetEncoding: 'url', publicMediaBaseUrl: 'http://127.0.0.1:4387', pollIntervalSeconds: 3, timeoutSeconds: 3600, authHeader: 'Authorization', authPrefix: 'Bearer ', jsonMode: false };
const presets = {
  h3: { ...base, name: 'MiniMax H3 · FL2VA', model: 'MiniMaxAI/MiniMax-H3' },
  ref: { ...base, name: 'MiniMax H3 · REF2VA', model: 'MiniMaxAI/MiniMax-H3', baseUrl: 'http://127.0.0.1:30011/v1', capabilities: ['REF2VA'] },
  planner: { ...base, name: '导演 Agent', kind: 'planner', protocol: 'openai', baseUrl: 'http://127.0.0.1:8000/v1', model: '', capabilities: [], submitPath: '/responses' },
  http: { ...base, name: '自定义视频模型', protocol: 'http', baseUrl: 'http://127.0.0.1:8001/v1', capabilities: ['FL2VA', 'REF2VA'], assetEncoding: 'data-url', submitPath: '/videos', pollPath: '/videos/{{jobId}}', bodyTemplate: { model: '{{model}}', prompt: '{{prompt}}', duration: '{{duration}}', aspect_ratio: '{{aspectRatio}}', first_frame: '{{firstFrame}}', last_frame: '{{lastFrame}}', reference_images: '{{referenceImages}}', reference_videos: '{{referenceVideos}}', reference_audios: '{{referenceAudios}}' } },
  comfy: { ...base, name: 'ComfyUI 本地工作流', protocol: 'comfyui', baseUrl: 'http://127.0.0.1:8188', capabilities: ['FL2VA', 'REF2VA'], bodyTemplate: {}, uploadPath: '/upload/image' },
};
export function Field({ label, children, hint }) { return <label className="field"><span>{label}</span>{children}{hint && <small>{hint}</small>}</label>; }
export function Models({ providers, act, refresh, busy }) {
  const [editing, setEditing] = useState(null);
  const save = async (data) => { await api('/providers', { method: 'POST', body: data }); setEditing(null); await refresh(); };
  return <section className="page models-page">
    <div className="page-title"><div><span className="eyebrow">MODEL CONNECTIONS</span><h1>让合适的模型，各司其职。</h1><p>一个理解需求的导演，任意数量的生成模型。</p></div><button className="primary" onClick={() => setEditing(structuredClone(presets.h3))}><Plus size={16}/>添加模型</button></div>
    <div className="connection-flow"><div><BrainCircuit/><span>Responses API<small>理解素材 · 编排分镜</small></span></div><ChevronRight/><div><Cpu/><span>MiniMax H3 / 自定义模型<small>FL2VA · REF2VA · 原生音频</small></span></div><ChevronRight/><div><FileJson/><span>本地合成<small>MP4 · SRT · 分镜 JSON</small></span></div></div>
    <div className="preset-heading"><h2>快速接入</h2><span>选择预设后填入你的服务地址</span></div>
    <div className="preset-grid">{[['planner', BrainCircuit, '导演 Agent', 'OpenAI Responses 兼容'], ['h3', Server, 'MiniMax H3', '本地 FL2VA / 文生视频'], ['ref', Server, 'MiniMax H3', '本地多模态 REF2VA'], ['comfy', Cable, 'ComfyUI', '导入 API workflow'], ['http', Cpu, '通用 HTTP', '自定义请求与结果映射']].map(([key, Icon, title, desc]) => <button key={key} className="preset" onClick={() => setEditing(structuredClone(presets[key]))}><Icon size={22}/><strong>{title}</strong><span>{desc}</span><Plus className="preset-plus" size={16}/></button>)}</div>
    <div className="preset-heading"><h2>已配置模型 <span className="count">{providers.length}</span></h2><span>密钥只在本机服务端保存</span></div>
    {providers.length === 0 ? <div className="empty-models"><Cable size={28}/><h3>把你的模型接进来</h3><p>先配置一个 Responses 理解模型，再添加 H3 本地服务。</p></div> : <div className="provider-list">{providers.map(p => <div className="provider-row" key={p.id}><div className={`provider-icon ${p.kind}`}>{p.kind === 'planner' ? <BrainCircuit/> : <Cpu/>}</div><div className="provider-info"><strong>{p.name}</strong><code>{p.baseUrl}</code></div><div className="tags">{p.kind === 'planner' ? <span className="tag purple">Responses</span> : p.capabilities.map(c => <span key={c} className={`tag ${c === 'REF2VA' ? 'purple' : ''}`}>{c}</span>)}</div><button disabled={busy} onClick={() => act(async () => { const r = await api(`/providers/${p.id}/check`, { method: 'POST' }); return r.message; })}>检查连接</button><button onClick={() => setEditing({ ...structuredClone(p), apiKey: '' })}>配置<ChevronRight size={14}/></button></div>)}</div>}
    {editing && <ModelEditor key={editing.id || editing.name} data={editing} busy={busy} close={() => setEditing(null)} onSave={data => act(() => save(data), '模型配置已保存')} onDelete={id => act(async () => { await api(`/providers/${id}`, { method: 'DELETE' }); setEditing(null); await refresh(); }, '已移除模型')}/>}
  </section>;
}
function ModelEditor({ data, close, onSave, onDelete, busy }) {
  const [form, setForm] = useState(data); const [body, setBody] = useState(JSON.stringify(data.bodyTemplate, null, 2)); const [extra, setExtra] = useState(JSON.stringify(data.extraBody || {}, null, 2)); const [headers, setHeaders] = useState(JSON.stringify(data.headers || {}, null, 2)); const [mapping, setMapping] = useState(JSON.stringify(data.responseMap, null, 2)); const [error, setError] = useState(''); const [confirmDelete, setConfirmDelete] = useState(false);
  const change = (key, value) => setForm(v => ({ ...v, [key]: value }));
  const submit = e => { e.preventDefault(); try { const parsed = { ...form, bodyTemplate: JSON.parse(body), extraBody: JSON.parse(extra), headers: JSON.parse(headers), responseMap: JSON.parse(mapping) }; setError(''); onSave(parsed); } catch (error) { setError(`JSON 格式有误：${error.message}`); } };
  return <Modal className="model-dialog" labelledBy="model-title" onClose={close}><form onSubmit={submit}><div className="dialog-header"><div><span className="eyebrow">CONNECTION SETUP</span><h2 id="model-title">{data.id ? '编辑模型' : '添加模型'}</h2></div><button type="button" className="icon-button" aria-label="关闭模型配置" onClick={close}><X/></button></div>
    <div className="dialog-body"><div className="two-col"><Field label="显示名称"><input required value={form.name} onChange={e => change('name', e.target.value)}/></Field><Field label="协议"><input readOnly value={{ h3: 'MiniMax H3 本地 API', openai: 'OpenAI Responses API', http: '通用 HTTP JSON', comfyui: 'ComfyUI API Workflow' }[form.protocol]}/></Field></div>
      <Field label="Base URL" hint={form.protocol === 'h3' ? 'H3 原生服务地址包含 /v1；FL2VA 和 REF2VA 可分别配置独立服务。' : '包含 API 前缀，例如 http://localhost:8000/v1'}><input required type="url" value={form.baseUrl} onChange={e => change('baseUrl', e.target.value)}/></Field>
      <div className="two-col"><Field label="Model ID"><input required={form.kind === 'planner'} placeholder="填入服务实际提供的模型 ID" value={form.model} onChange={e => change('model', e.target.value)}/></Field><Field label="API Key" hint={data.hasApiKey ? '已保存密钥，留空保持原值' : '本地无鉴权服务可以留空'}><input autoComplete="new-password" type="password" value={form.apiKey} onChange={e => change('apiKey', e.target.value)}/></Field></div>
      {form.kind === 'video' && <Field label="视频生成能力"><div className="check-row">{['FL2VA', 'REF2VA'].map(mode => <label key={mode}><input type="checkbox" checked={form.capabilities.includes(mode)} onChange={e => change('capabilities', e.target.checked ? [...form.capabilities, mode] : form.capabilities.filter(c => c !== mode))}/>{mode === 'FL2VA' ? 'FL2VA · 首尾帧 / 文生视频' : 'REF2VA · 多模态参考'}</label>)}</div></Field>}
      {form.kind === 'planner' && <><Field label="Responses 路径"><input value={form.submitPath} onChange={e => change('submitPath', e.target.value)}/></Field><label className="check-row"><input type="checkbox" checked={form.jsonMode} onChange={e => change('jsonMode', e.target.checked)}/>启用 JSON 输出模式（需服务支持）</label><p className="note">图片直接送入理解模型；视频提取三个关键帧。音频供 REF2VA 生成使用，通用 Responses 不直接解析音频。</p></>}
      {form.kind === 'video' && form.protocol !== 'comfyui' && <><div className="two-col"><Field label="素材传递方式"><select value={form.assetEncoding} onChange={e => change('assetEncoding', e.target.value)}><option value="url">HTTP URL</option><option value="data-url">Base64 Data URL</option></select></Field><Field label="素材可访问根地址"><input value={form.publicMediaBaseUrl} onChange={e => change('publicMediaBaseUrl', e.target.value)} placeholder="http://127.0.0.1:4387"/></Field></div>{form.protocol === 'h3' && <p className="note">默认地址适用于同机 H3 服务。容器或远程 H3 需自行提供可访问的媒体服务地址，或确认服务支持 Data URL 后切换。</p>}</>}
      {form.protocol === 'http' && <><div className="two-col"><Field label="提交路径"><input required value={form.submitPath} onChange={e => change('submitPath', e.target.value)}/></Field><Field label="轮询路径"><input value={form.pollPath} onChange={e => change('pollPath', e.target.value)}/></Field></div><Field label="结果查询路径（可选）"><input value={form.resultPath} onChange={e => change('resultPath', e.target.value)}/></Field><Field label="响应映射 JSON"><textarea className="code-input" rows={8} value={mapping} onChange={e => setMapping(e.target.value)}/></Field></>}
      {['http', 'comfyui'].includes(form.protocol) && <><Field label={form.protocol === 'comfyui' ? 'ComfyUI API Workflow JSON' : '请求体模板 JSON'} hint="完整变量保留数组和数字类型。支持 prompt、duration、aspectRatio、firstFrame、lastFrame、referenceImages、referenceVideos、referenceAudios、model、seed。"><textarea className="code-input" rows={12} value={body} onChange={e => setBody(e.target.value)}/></Field><label className="file-import"><FileJson size={16}/>导入 JSON<input type="file" accept=".json" onChange={async e => { try { const text = await e.target.files[0]?.text(); if (text) { JSON.parse(text); setBody(text); } } catch { setError('不是有效的 JSON 文件'); } }}/></label>{form.protocol === 'comfyui' && <p className="note">导入「Save (API Format)」格式，输入节点的值可替换成 {"{{prompt}}"}、{"{{firstFrame}}"} 或 {"{{referenceImages.0}}"}。工作流必须包含视频保存节点。</p>}</>}
      <details><summary>高级配置</summary><div className="two-col"><Field label="鉴权 Header"><input value={form.authHeader} onChange={e => change('authHeader', e.target.value)}/></Field><Field label="鉴权前缀（含空格）"><input value={form.authPrefix} onChange={e => change('authPrefix', e.target.value)}/></Field></div><Field label="额外 Headers JSON"><textarea className="code-input" rows={3} value={headers} onChange={e => setHeaders(e.target.value)}/></Field><Field label="额外参数 JSON"><textarea className="code-input" rows={5} value={extra} onChange={e => setExtra(e.target.value)}/></Field><div className="two-col"><Field label="轮询间隔（秒）"><input type="number" min="1" max="60" value={form.pollIntervalSeconds} onChange={e => change('pollIntervalSeconds', Number(e.target.value))}/></Field><Field label="任务超时（秒）"><input type="number" min="10" max="14400" value={form.timeoutSeconds} onChange={e => change('timeoutSeconds', Number(e.target.value))}/></Field></div>{data.hasApiKey && <label className="check-row"><input type="checkbox" checked={Boolean(form.clearApiKey)} onChange={e => change('clearApiKey', e.target.checked)}/>清除已保存的 API Key</label>}</details>
      {error && <p role="alert" className="error-text">{error}</p>}
    </div><div className="dialog-footer">{data.id && <button disabled={busy} type="button" className="danger" onClick={() => confirmDelete ? onDelete(data.id) : setConfirmDelete(true)}><Trash2 size={15}/>{confirmDelete ? '确认移除模型' : '移除'}</button>}<span className="spacer"/><button type="button" onClick={close}>取消</button><button disabled={busy} className="primary" type="submit"><Save size={16}/>保存配置</button></div></form></Modal>;
}
